# Copyright (c) 2026 Carles Marin. All rights reserved.
# Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
#
# The moment cone of the multiplet lattice, computed EXACTLY: its extreme rays, its dual
# description, the index of the sublattice the eight generators actually reach, and the Hilbert
# basis of the resulting affine semigroup.  Written for the Part VII figure, and it is the one
# object in that paper that only a computer algebra system can certify.
#
# The map: a bulk content n in ZZ^8_{>=0} gives (A_4, 8D) = (-18, -27) + sum_j n_j (a_j, d_j).
# Everything the model can realise is therefore the gauge offset plus the affine semigroup
# generated by the eight columns.  Section 8 of the paper optimises over its rational relaxation;
# this file computes the integral object underneath it.

NAMES = ["7(+,+)", "7(+,-)", "28(+,+)", "28(+,-)", "48(+,+)", "48(+,-)", "84(+,+)", "84(+,-)"]
GEN = [(0, -6), (1, 8), (17, 16), (4, 2), (18, 0), (8, 28), (68, 10), (109, 80)]
OFF = (-18, -27)

print("=" * 88)
print("1 -- THE CONE, exactly")
print("=" * 88)
C = Cone(GEN)
print("  generators given      : %d" % len(GEN))
print("  extreme rays          : %s" % [tuple(r) for r in C.rays()])
print("  dual description      : %s" % [tuple(h) for h in C.facet_normals()])
print("  is it simplicial      : %s   full-dimensional: %s" % (C.is_simplicial(), C.dim() == 2))
print()
print("  which generators are EXTREME, and which are redundant:")
rays = [vector(ZZ, r) for r in C.rays()]
for nm, g in zip(NAMES, GEN):
    v = vector(ZZ, g)
    extreme = any(v == r or (v[0] * r[1] == v[1] * r[0] and v.dot_product(r) > 0
                             and gcd(v[0], v[1]) * r == v) for r in rays)
    on = [i for i, r in enumerate(rays) if v[0] * r[1] - v[1] * r[0] == 0]
    print("     %-10s (%4d,%4d)   %s" % (nm, g[0], g[1],
          "EXTREME RAY" if on else "interior to the cone"))

print()
print("=" * 88)
print("2 -- THE SUBLATTICE the eight generators actually reach")
print("=" * 88)
M = matrix(ZZ, GEN).transpose()
L = M.column_module()                       # the subgroup of ZZ^2 generated by the columns
print("  subgroup generated    : %s" % L)
print("  index in ZZ^2         : %s" % L.index_in(ZZ^2))
print("  Smith normal form     : %s" % M.smith_form()[0].diagonal()[:2])
print()
print("  the congruence, read off the quotient  ZZ^2 / L :")
Q = (ZZ^2) / L
print("     quotient group     : %s   order %s" % (Q, Q.cardinality()))
for nm, g in zip(NAMES, GEN):
    print("     %-10s a+d = %5d  (mod 3 -> %d) ,  d = %4d (mod 2 -> %d)"
          % (nm, g[0] + g[1], (g[0] + g[1]) % 3, g[1], g[1] % 2))
print("     gauge      a+d = %5d  (mod 3 -> %d) ,  d = %4d (mod 2 -> %d)"
      % (OFF[0] + OFF[1], (OFF[0] + OFF[1]) % 3, OFF[1], OFF[1] % 2))
print()
print("  So every REALISED point sits in  (-18,-27) + L, an index-%s coset: that is the mod-6"
      % L.index_in(ZZ^2))
print("  law of the paper, here as a lattice index rather than as a congruence.")

print()
print("=" * 88)
print("3 -- THE HILBERT BASIS: the minimal moment-vectors that generate everything")
print("=" * 88)
HB = None
try:
    Cn = Cone(GEN)
    HB = [tuple(v) for v in Cn.semigroup_generators()]
    print("  Hilbert basis of the cone over ZZ^2 (%d elements):" % len(HB))
    for v in sorted(HB):
        print("     %s" % (v,))
except Exception as e:
    print("  semigroup_generators unavailable: %s" % e)

print()
print("  and the semigroup ACTUALLY generated by the eight multiplets is smaller than the cone's")
print("  integral points: a Hilbert basis element that is not a non-negative integer combination of")
print("  the eight is a moment vector the model CANNOT realise.")
gap = []
if HB:
    for v in sorted(HB):
        P = MixedIntegerLinearProgram(maximization=False, solver="GLPK")
        y = P.new_variable(integer=True, nonnegative=True)
        P.add_constraint(sum(y[j] * GEN[j][0] for j in range(8)) == v[0])
        P.add_constraint(sum(y[j] * GEN[j][1] for j in range(8)) == v[1])
        P.set_objective(sum(y[j] for j in range(8)))
        try:
            P.solve()
            ok = True
        except Exception:
            ok = False
        print("     %-12s reachable by the eight multiplets : %s" % (str(v), ok))
        if not ok:
            gap.append(v)
print("  unreachable Hilbert-basis elements: %s" % (gap if gap else "NONE"))

print()
print("=" * 88)
print("4 -- THE LATTICE POINTS the figure will draw")
print("=" * 88)
TMAX, KMAX = 700, 60
pts = []
for t in range(-18, TMAX + 1):
    for k in range(1, KMAX + 1, 2):
        if (t + k) % 3:
            continue
        if vector(ZZ, (t - OFF[0], k - OFF[1])) in L and C.contains(vector(ZZ, (t - OFF[0], k - OFF[1]))):
            pts.append((t, k))
print("  admissible (A_4, 8D) with A_4 <= %d, 8D <= %d : %d" % (TMAX, KMAX, len(pts)))
print("  (of the %d integer points in that box, so a density of %.4f)"
      % (((TMAX + 19) * (KMAX + 1) // 2), len(pts) / float((TMAX + 19) * (KMAX + 1) // 2)))

import json


def py(o):
    """Sage Integers are not JSON serialisable; cast the whole tree to plain Python."""
    if isinstance(o, (list, tuple)):
        return [py(x) for x in o]
    if isinstance(o, dict):
        return {str(k): py(v) for k, v in o.items()}
    if isinstance(o, str) or o is None:
        return o
    return int(o)


out = py(dict(generators=GEN, names=NAMES, offset=OFF,
              rays=[tuple(r) for r in C.rays()],
              facet_normals=[tuple(h) for h in C.facet_normals()],
              sublattice_index=L.index_in(ZZ^2),
              hilbert_basis=sorted(HB) if HB else None,
              unreachable=gap, points=pts, box=[TMAX, KMAX]))
out["names"] = NAMES
open("outputs/cone_moments.json", "w").write(json.dumps(out, indent=1))
print()
print("written: outputs/cone_moments.json")
