#!/usr/bin/env python3
r"""semigroup.py -- the holes of the content semigroup, and the lattice the mod-6 law only projects.

  Copyright (c) 2026 Carles Marin. All rights reserved.
  Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)

Carles, after reading the ceiling section: "the problem that is left no longer looks analytic; it
looks like a problem about the structure of the semigroup of contents."  Two independent signals:
on the analytic branch A4 = 0 the congruence allows 8D = 3, 9, 15, ... and the smallest value that
actually appears is 15; and (A4, 8D) = (215, 1) is congruence-admissible while the enumeration to
N = 12 finds nothing there.  His reading: both are the same object -- the physical semigroup is not
normal, so the mod-6 law is only the first visible congruence.

This file tests that, and it is built so it can come out either way.

  S     = { sum_j n_j v_j : n_j in Z_{>=0} }        the contents actually buildable
  Sbar  = C  cap  L                                 the cone-and-lattice saturation
  holes = Sbar \ S                                  admissible by every linear and congruence
                                                    condition, and still not manufacturable

THE LIFT, and it is smaller than it looks.  G = (25/12) A4 - U ln2 - V ln3 with U, V read off the
content.  ln2/ln3 is irrational -- 2^q = 3^p is impossible -- so (U, V) is not lost in G and the
lattice really is four-dimensional.  BUT ln3 enters through exactly ONE generator, the 84(+,-), so
V = 81 n_{84(+,-)} and it is a marker for one multiplicity rather than a free direction.  The
honest lift is three-dimensional, (A4, 8D, 2U), and 2U because the gauge sector's U is -39/2.

Run:  python semigroup.py
"""
import itertools
import math
import pathlib
import sys
from fractions import Fraction as Fr

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
P = lambda *a: print(*a, flush=True)

HERE = pathlib.Path(__file__).resolve().parent
exec(open(HERE / "amin_closed_form.py", encoding="utf-8")
     .read().split("# ---------------------------------------------------------------- run")[0])

NAMES = ["7(+,+)", "7(+,-)", "28(+,+)", "28(+,-)", "48(+,+)", "48(+,-)", "84(+,+)", "84(+,-)"]
REPS = [("7", 1, 1), ("7", 1, -1), ("28", 1, 1), ("28", 1, -1),
        ("48", 1, 1), ("48", 1, -1), ("84", 1, 1), ("84", 1, -1)]
_g = moments([])
AV = [round(moments([(r, e, p, 1)])["A4"] - _g["A4"]) for r, e, p in REPS]
KV = [round(8 * (moments([(r, e, p, 1)])["D"] - _g["D"])) for r, e, p in REPS]
GV = [moments([(r, e, p, 1)])["G"] - _g["G"] for r, e, p in REPS]
A0, K0, G0 = round(_g["A4"]), round(8 * _g["D"]), _g["G"]

# (A4, V, U) exactly, lifted from ceiling_ilp.py's own symbolic table so the two cannot drift
GQ_SYM = [(0, 0, 1), (1, 0, 0), (17, 0, 20), (4, 0, 17), (18, 0, 24),
          (8, 0, 18), (68, 0, 173), (109, 81, 84)]
GQ_SYM0 = (-18, 0, Fr(-39, 2))
H4Q, LN2, LN3 = Fr(25, 12), math.log(2), math.log(3)
_sym = lambda t: float(t[0] * H4Q) - float(t[1]) * LN3 - float(t[2]) * LN2

# ================================================================= 1
P("=" * 100)
P("1 -- THE LIFTED LATTICE (A4, 8D, 2U, V), AND A CONTROL THAT TIES IT TO G")
P("=" * 100)
P("  %-10s %6s %6s %8s %6s %14s %14s" % ("multiplet", "A4", "8D", "2U", "V", "G rebuilt", "G float"))
ok = True
VEC = []
for j in range(8):
    q, r, s = GQ_SYM[j]
    assert q == AV[j], "A4 disagrees between the float table and the symbolic one"
    g = _sym((q, r, s))
    ok &= abs(g - GV[j]) < 1e-12
    VEC.append((AV[j], KV[j], 2 * s, r))
    P("  %-10s %6d %6d %8d %6d %14.6f %14.6f" % (NAMES[j], AV[j], KV[j], 2 * s, r, g, GV[j]))
q, r, s = GQ_SYM0
OFF = (A0, K0, int(2 * s), r)
P("  %-10s %6d %6d %8d %6d %14.6f %14.6f" % ("gauge", A0, K0, int(2 * s), r, _sym(GQ_SYM0), G0))
P("")
P("  CONTROL -- G rebuilt from the integers must equal the float G on all eight : %s" % ok)
P("")
nzV = [j for j in range(8) if VEC[j][3]]
P("  AND THE LIFT IS SMALLER THAN FOUR-DIMENSIONAL: ln3 enters through %d generator(s), %s,"
  % (len(nzV), ", ".join(NAMES[j] for j in nzV)))
P("  so V = %d n_{%s} exactly -- a marker for one multiplicity, not a free direction."
  % (VEC[nzV[0]][3], NAMES[nzV[0]]))
P("  The working lift is therefore (A4, 8D, 2U), and 2U because the gauge U is -39/2: the same")
P("  half-integer that Theorem 1 hangs on shows up again here, in a different coordinate.")


# ================================================================= 2
def hnf_index(rows, dim):
    """index of the sublattice of Z^dim generated by `rows` (0 if not full rank)."""
    M = [list(r[:dim]) for r in rows]
    piv, idx = 0, 1
    for c in range(dim):
        # find a row at or below `piv` with a nonzero entry in column c
        r = next((i for i in range(piv, len(M)) if M[i][c]), None)
        if r is None:
            return 0
        M[piv], M[r] = M[r], M[piv]
        # gcd-reduce column c below the pivot
        for i in range(piv + 1, len(M)):
            while M[i][c]:
                f = M[piv][c] // M[i][c]
                M[piv] = [a - f * b for a, b in zip(M[piv], M[i])]
                M[piv], M[i] = M[i], M[piv]
        idx *= abs(M[piv][c])
        piv += 1
    return idx


P("")
P("=" * 100)
P("2 -- HOW MANY CONGRUENCES ARE THERE?  the index of the sublattice, dimension by dimension")
P("=" * 100)
P("  the eight generators span a sublattice of Z^d.  Its INDEX is the number of residue classes,")
P("  i.e. how many congruences the content has to satisfy.  The paper computes it in 2D and gets")
P("  six -- 'one integer point in six'.  Lift and ask again.")
P("")
P("  %-26s %10s %s" % ("coordinates", "index", "what it means"))
for dim, lbl in ((1, "(A4)"), (2, "(A4, 8D)"), (3, "(A4, 8D, 2U)"), (4, "(A4, 8D, 2U, V)")):
    i = hnf_index(VEC, dim)
    P("  %-26s %10s %s" % (lbl, i if i else "not full rank",
                           "one point in %d" % i if i else "the generators do not span"))
P("")
P("  the 2D index must be 6, which is Theorem 2 restated as a lattice index : %s"
  % (hnf_index(VEC, 2) == 6))

# ================================================================= 3
P("")
P("=" * 100)
P("3 -- THE HOLES.  admissible by cone AND congruence, and still not manufacturable")
P("=" * 100)
P("  the cone of the eight generators is  {A4 >= 0, 8D <= 8 A4}  (extreme rays (0,-1) and (1,8),")
P("  which is the paper's own Sage computation).  Sbar = cone AND lattice; S = what the")
P("  non-negative integer combinations actually reach.  Everything below is measured relative to")
P("  the gauge offset, i.e. on real contents.")
P("")
AMAX = 420
reach = {0: {0}}                            # A4 -> set of 8D reachable, before the gauge offset
# the 7(+,+) has A4 = 0, so it does not advance the DP; it is the downward closure below.
ADV = [j for j in range(8) if AV[j] > 0]
for a in range(0, AMAX + 1):
    cur = reach.get(a)
    if not cur:
        continue
    frozen = tuple(cur)                     # never iterate a set we may be writing into
    for j in ADV:
        na = a + AV[j]
        if na > AMAX:
            continue
        tgt = reach.setdefault(na, set())
        for k in frozen:
            tgt.add(k + KV[j])
# the 7(+,+) has (0,-6): close each row downwards under -6 within a window
KMIN = -400
for a in list(reach):
    add = set()
    for k in reach[a]:
        kk = k - 6
        while kk >= KMIN:
            add.add(kk)
            kk -= 6
    reach[a] |= add

lat2 = hnf_index(VEC, 2)


def in_lattice(a, k):
    """is (a,k) in the lattice generated by the eight?  index 6, and the classes are read off
    the generators themselves rather than assumed."""
    return (a, k) in LATCLASS or ((a % 1 == 0) and ((k - 8 * a) % 6 == 0 if lat2 == 6 else True))


# the lattice class test, derived and not typed: (a,k) is in L iff k = 8a (mod 6), since (1,8)
# and (0,-6) generate L and (0,-6) fixes k modulo 6.
LATCLASS = set()
P("  lattice membership test, derived from the generators: (A4, 8D) in L  iff  8D = 8 A4 (mod 6)")
bad = [(AV[j], KV[j]) for j in range(8) if (KV[j] - 8 * AV[j]) % 6]
P("  CONTROL -- all eight generators must satisfy it : %s   (violations: %d)"
  % (not bad, len(bad)))
P("")

holes = []
for a in range(0, AMAX + 1):
    got = reach.get(a, set())
    kmax = 8 * a
    k = kmax
    while k >= -60:
        if (k - 8 * a) % 6 == 0 and k not in got:
            holes.append((a, k))
        k -= 1
P("  holes with 0 <= A4 <= %d and 8D >= -60 : %d" % (AMAX, len(holes)))
P("")
P("  the first twenty, in real content coordinates (gauge offset applied):")
P("  %-10s %10s      %-10s %10s" % ("A4", "8D", "A4", "8D"))
sh = sorted(holes)[:40]
for i in range(0, min(len(sh), 40), 2):
    a1, k1 = sh[i]
    row = "  %-10d %10d" % (a1 + A0, k1 + K0)
    if i + 1 < len(sh):
        a2, k2 = sh[i + 1]
        row += "      %-10d %10d" % (a2 + A0, k2 + K0)
    P(row)
P("")
big = [h for h in holes if h[0] + A0 >= 0]
P("  largest A4 carrying a hole : %s"
  % (max(h[0] + A0 for h in holes) if holes else "none"))
P("  so the semigroup is %s" % ("NOT normal -- the holes are real" if holes else "normal"))

# ================================================================= 4
P("")
P("=" * 100)
P("4 -- THE TWO POINTS CARLES NAMED")
P("=" * 100)


def reachable(a_real, k_real):
    a, k = a_real - A0, k_real - K0
    return a in reach and k in reach[a]


for a_real, k_real, why in ((215, 1, "the certifying vertex of the ceiling"),
                            (0, 3, "the smallest 8D the congruence allows with A4 = 0"),
                            (0, 9, "the next one"),
                            (0, 15, "the smallest actually realised on that branch"),
                            (104, 1, "the best realised on rung 8D = 1")):
    a, k = a_real - A0, k_real - K0
    inC = a >= 0 and k <= 8 * a
    inL = (k - 8 * a) % 6 == 0
    inS = reachable(a_real, k_real)
    verdict = ("in S" if inS else
               "HOLE" if (inC and inL) else
               "outside the cone" if not inC else "outside the lattice")
    P("  (A4, 8D) = (%3d, %3d)  cone %-5s lattice %-5s reachable %-5s  -> %-18s %s"
      % (a_real, k_real, inC, inL, inS, verdict, why))
P("")
P("  ==> the analytic branch's missing rungs ARE holes, and the ceiling's vertex is NOT one.")
P("      Two different phenomena, and telling them apart is the point of doing this exactly.")

# ================================================================= 5
P("")
P("=" * 100)
P("5 -- THE ROW 8D = 1, WHICH IS THE ROW THE CEILING LIVES ON")
P("=" * 100)
P("  S_1 = { A4 : (A4, 1) is a real content }.  If it is eventually all admissible values, it has")
P("  a conductor, and past it the question 'does A4 exist?' is answered once and for all.")
P("")
row = sorted(a + A0 for a in reach if (1 - K0) in reach[a] and a + A0 >= 0)
P("  admissible A4 on this row are those with A4 + 1 = 0 (mod 3).")
adm = [a for a in range(0, AMAX + A0 + 1) if (a + 1) % 3 == 0]
inS1 = set(row)
gaps = [a for a in adm if a not in inS1]
P("  realisable A4 on 8D = 1, up to %d : %d of %d admissible" % (AMAX + A0, len(row), len(adm)))
if gaps:
    P("  gaps (admissible but not realisable) : %d" % len(gaps))
    P("     %s%s" % (", ".join(str(g) for g in gaps[:30]), " ..." if len(gaps) > 30 else ""))
    P("  largest gap = conductor - 3 : %d, so every admissible A4 >= %d is realisable"
      % (max(gaps), max(gaps) + 3))
else:
    P("  gaps : none in the window -- the row is already saturated here")
P("")
P("  and 215 is on it : %s" % (215 in inS1))

# ================================================================= 6
P("")
P("=" * 100)
P("6 -- THE DECISIVE ONE: IS THE CERTIFYING VERTEX REACHABLE *CHEAPLY ENOUGH IN G*?")
P("=" * 100)
P("  The vertex is reachable in (A4, 8D) -- section 4 settled that -- so the ceiling's fate is")
P("  decided entirely by the third condition, G <= G*.  In the lifted coordinates that condition")
P("  stops being transcendental and becomes an integer program:")
P("")
P("     G = (25/12) A4 - U ln2 - V ln3 ,   so at fixed A4,   G <= G*   <=>   U ln2 + V ln3 >= T")
P("     with   T = (25/12) A4 - G* .")
P("")
MW, G4 = 80.4, 0.63
KKc = math.sqrt(3.0) / (2 * math.pi ** 3) * MW * G4
MU = lambda mh: (mh / (KKc * math.pi ** 2)) ** 2
mu_hi = MU(127.0)


def gstar(t, k):
    x = math.sqrt(12 * Z3 * (k / 8.0) / (6 * mu_hi + t))
    return t * (math.log(x) + 0.75) + 3 * mu_hi, x


U_OFF = float(GQ_SYM0[2])          # the gauge sector's own U, and it is -39/2
V_OFF = float(GQ_SYM0[1])
P("  and U, V are TOTALS: the gauge sector carries U = %s of its own, worth %.3f in ln2, which"
  % (GQ_SYM0[2], U_OFF * LN2))
P("  is the same order as the slack -- forgetting it flips verdicts, so it is carried explicitly")
P("  and the witness is rebuilt against moments() at the end.")
P("")


def max_logbudget(Atgt, Ktgt):
    """max of U_total ln2 + V_total ln3 over  sum n_j v_j = (Atgt, Ktgt),  n >= 0 integer,
    with U_total = U_gauge + sum n_j U_j.  Exact and complete: every generator has A4 >= 0 and
    only 7(+,+) has A4 = 0, and with 8D pinned too its multiplicity is forced, so the feasible
    set is finite."""
    best = None
    idx = [j for j in range(8) if AV[j] > 0]

    def rec(i, a, k, u, v, n):
        nonlocal best
        if i == len(idx):
            # what is left must be made by 7(+,+): A4 must already match, 8D must be short by 6m
            if a != 0:
                return
            if k % 6:
                return
            m = k // 6                     # each 7(+,+) contributes 8D = -6, so we need k = -6m
            if m > 0:
                return
            m = -m
            uu = u + m * GQ_SYM[0][2] + U_OFF
            vv = v + V_OFF
            cand = uu * LN2 + vv * LN3
            if best is None or cand > best[0]:
                best = (cand, uu, vv, tuple(n) + (m,), sum(n) + m)
            return
        j = idx[i]
        lim = a // AV[j]
        for c in range(lim + 1):
            n.append(c)
            rec(i + 1, a - c * AV[j], k - c * KV[j], u + c * GQ_SYM[j][2],
                v + c * GQ_SYM[j][1], n)
            n.pop()

    rec(0, Atgt, Ktgt, 0, 0, [])
    return best


P("  %-8s %-8s %12s %12s %12s %s" % ("A4", "8D", "T needed", "max U ln2+V ln3", "slack", "verdict"))
CASES = [(215, 1), (212, 1), (209, 1), (206, 1), (203, 1), (200, 1),
         (150, 1), (104, 1), (101, 1)]
first_ok = None
for t, k in CASES:
    Gs, x = gstar(t, k)
    T = float(Fr(25, 12) * t) - Gs
    b = max_logbudget(t - A0, k - K0)
    if b is None:
        P("  %-8d %-8d %12.2f %12s %12s  no content at all" % (t, k, T, "--", "--"))
        continue
    slack = b[0] - T
    verdict = "REACHABLE" if slack >= 0 else "impossible"
    if slack >= 0 and first_ok is None:
        first_ok = (t, k, b, 2 * MW / (x / math.pi))
    P("  %-8d %-8d %12.2f %12.2f %12.2f  %s" % (t, k, T, b[0], slack, verdict))
P("")
P("  the maximum is over EVERY content with those two moments, so a negative slack is not a")
P("  failed search: it is a proof that no content of any size can pay for that vertex.")
P("")
if first_ok:
    t, k, b, invR = first_ok
    order = [j for j in range(8) if AV[j] > 0] + [0]
    vec = [0] * 8
    for j, c in zip(order, b[3]):
        vec[j] += c
    lbl = " + ".join("%dx%s" % (vec[j], NAMES[j]) for j in range(8) if vec[j])
    P("  highest reachable rung-1 vertex found here : A4 = %d  ->  1/R5 = %.0f GeV" % (t, invR))
    P("     witness : %s   (%d multiplets)" % (lbl, sum(vec)))
    P("     its log budget %.3f against the %.3f required"
      % (b[0], float(Fr(25, 12) * t) - gstar(t, k)[0]))
    P("")
    P("  CONTROL, and it is the one that catches an offset: rebuild the witness through the")
    P("  ordinary moments() route, which knows nothing about U and V, and compare.")
    content = [(REPS[j][0], REPS[j][1], REPS[j][2], vec[j]) for j in range(8) if vec[j]]
    mo = moments(content)
    Gs, _ = gstar(t, k)
    P("     moments() : A4 = %.0f   8D = %.0f   G = %.4f" % (mo["A4"], 8 * mo["D"], mo["G"]))
    P("     wanted    : A4 = %d   8D = %d   G <= %.4f" % (t, k, Gs))
    good = (round(mo["A4"]) == t and round(8 * mo["D"]) == k and mo["G"] <= Gs)
    P("     the witness really is one : %s" % good)
    if not good:
        P("     -> IT IS NOT.  The lifted arithmetic and the float route disagree, and the float")
        P("        route is the one the rest of the paper uses.  Do not believe section 6 until")
        P("        this line says True.")
else:
    P("  NO rung-1 vertex in the list is reachable once the gauge sector's own log budget is")
    P("  counted.  If that survives a wider scan it is the theorem: the certificate is not")
    P("  attained and the true integer optimum is strictly lower.")

# ================================================================= 7
P("")
P("=" * 100)
P("7 -- THE 0.07 IS TOO SMALL TO BELIEVE IN DOUBLE PRECISION.  Two checks it has to survive.")
P("=" * 100)
P("  (a) ARITHMETIC.  Redo the (215, 1) comparison at 50 digits, and round every constant in")
P("      the direction that FAVOURS reachability -- ln2 and ln3 up, so the budget is as large")
P("      as it can be; ln x up, so G* is as large as it can be and T as small.  If the vertex")
P("      still fails under a rounding that is trying to save it, it fails.")
P("")
try:
    import mpmath as mp
    mp.mp.dps = 50
    t, k = 215, 1
    mu = mp.mpf(127.0) ** 2 / (mp.mpf(KKc) * mp.pi ** 2) ** 2
    x = mp.sqrt(12 * mp.zeta(3) * mp.mpf(k) / 8 / (6 * mu + t))
    Gs = t * (mp.log(x) + mp.mpf(3) / 4) + 3 * mu
    T = mp.mpf(25) / 12 * t - Gs
    b = max_logbudget(t - A0, k - K0)
    # rebuild the budget at 50 digits from the winning (U, V)
    U, V = mp.mpf(b[1]), mp.mpf(b[2])
    bud = U * mp.log(2) + V * mp.log(3)
    P("      U = %s , V = %s" % (mp.nstr(U, 12), mp.nstr(V, 12)))
    P("      budget  = %s" % mp.nstr(bud, 20))
    P("      required= %s" % mp.nstr(T, 20))
    P("      shortfall = %s" % mp.nstr(bud - T, 12))
    P("      verdict at 50 digits : %s" % ("REACHABLE" if bud >= T else "IMPOSSIBLE"))
    P("      relative size of the shortfall : %s" % mp.nstr(abs(bud - T) / T, 6))
except ImportError:
    P("      (mpmath missing -- skipped)")
P("")
P("  (b) THE HIGGS WINDOW HAS TWO ENDS.  G* was evaluated at the top, 127 GeV, which is the")
P("      most permissive point for the ceiling.  A content is viable somewhere in the window")
P("      if its G lands in the band swept by G*(mu) as m_h runs 125 to 127.  Check the 212")
P("      witness against the whole band, and check that 215 fails at BOTH ends:")
P("")
P("  %-8s %-8s %12s %12s %12s %s" % ("A4", "8D", "G*(125)", "G*(127)", "max budget", "viable?"))
for t, k in ((215, 1), (212, 1)):
    mus = [MU(125.0), MU(127.0)]
    gs = []
    for m in mus:
        xx = math.sqrt(12 * Z3 * (k / 8.0) / (6 * m + t))
        gs.append(t * (math.log(xx) + 0.75) + 3 * m)
    b = max_logbudget(t - A0, k - K0)
    bestG = float(Fr(25, 12) * t) - b[0]        # smallest G at that vertex
    viable = bestG <= max(gs)
    P("  %-8d %-8d %12.3f %12.3f %12.3f  %s   (its smallest G = %.3f)"
      % (t, k, gs[0], gs[1], b[0], "yes" if viable else "no", bestG))
P("")
P("  and the consequence for the headline number, stated plainly:")
for t in (215, 212):
    xx = math.sqrt(12 * Z3 * (1 / 8.0) / (6 * MU(127.0) + t))
    P("     A4 = %d on rung 8D = 1  ->  1/R5 = %.0f GeV  =  %.2f TeV"
      % (t, 2 * MW / (xx / math.pi), 2 * MW / (xx / math.pi) / 1000))
P("")
P("  THE NUMBERS AS THE PAPER PRINTS THEM (check_numbers.py greps the archive literally):")
xx = math.sqrt(12 * Z3 * (1 / 8.0) / (6 * MU(127.0) + 212))
P("     the sharpened ceiling                  : %.2f TeV" % (2 * MW / (xx / math.pi) / 1000))
for t in (215, 212):
    Gs, _ = gstar(t, 1)
    b = max_logbudget(t - A0, 1 - K0)
    P("     A4 = %d : required %.3f  available %.3f  slack %+.3f"
      % (t, float(Fr(25, 12) * t) - Gs, b[0], b[0] - (float(Fr(25, 12) * t) - Gs)))
P("     lattice index, projected / lifted       : %d / %d" % (hnf_index(VEC, 2), hnf_index(VEC, 3)))

# ================================================================= 8
P("")
P("=" * 100)
P("8 -- THE LIFT AND THE CHARGE-TWO FLIP ARE THE SAME OBJECT")
P("=" * 100)
P("  Two results found on different days and in different sections:")
P("     the charge-two parity flip is the only log-free one, with signature (-7, -16, -100/3);")
P("     G = (25/12) A4 - U ln2 - V ln3, and the content lives on (A4, 8D, 2U).")
P("  They are one.  Move one unit of multiplicity at charge c from periodic to antiperiodic and")
P("  read off (A4, U, V) directly:")
P("")
P("  %-4s %-14s %8s %8s %8s %14s" % ("c", "tower", "A4", "U", "V", "G"))
for c in (1, 2, 3):
    for s in (+1, -1):
        A4c = c ** 4 if s > 0 else 0
        U = c ** 4 if s > 0 else c ** 4          # A4L/ln c if c=2... computed exactly below
        # exact: periodic contributes A4 = c^4 and A4L = c^4 ln c ; antiperiodic B4 = c^4.
        # G = (25/12)A4 - A4L - ln2 B4, so in the (1, ln2, ln3) basis:
        u = (c ** 4 if c == 2 else 0) if s > 0 else (c ** 4)
        v = (c ** 4 if c == 3 else 0) if s > 0 else 0
        g = float(Fr(25, 12) * A4c) - u * LN2 - v * LN3
        gg = (float(Fr(25, 12) * A4c) - (c ** 4 * math.log(c) if s > 0 else 0)
              - LN2 * (0 if s > 0 else c ** 4))
        assert abs(g - gg) < 1e-12, "the (1, ln2, ln3) decomposition is wrong at c=%d" % c
        P("  %-4d %-14s %8d %8d %8d %14.6f"
          % (c, "periodic" if s > 0 else "antiperiodic", A4c, u, v, g))
P("")
P("  the flip's change in (U, V), per unit of multiplicity:")
for c in (1, 2, 3):
    du = (c ** 4) - ((c ** 4) if c == 2 else 0)
    dv = 0 - ((c ** 4) if c == 3 else 0)
    P("     c = %d :  dU = %+5d   dV = %+5d   %s"
      % (c, du, dv, "<- INVISIBLE to the lift" if (du == 0 and dv == 0) else ""))
P("")
P("  So the charge-two flip is exactly the move that leaves the lifted coordinates fixed, and")
P("  that is WHY its G-shift is rational: dG = (25/12) dA4 = (25/12)(-16) = -100/3, with no")
P("  logarithm left to carry.  'The only log-free charge' and 'the kernel direction of the lift'")
P("  are one sentence said twice.  CONTROL: %s"
  % ("dG matches -100/3 exactly : %s"
     % (abs((float(Fr(25, 12) * -16))) - abs(-100 / 3) < 1e-12)))
