# Independent instrument for vgiq_anchor.py: the Wilson-line charges from Sage's Lie theory,
# not from generators typed by hand.  If the two disagree, the hand-rolled ones are wrong.
#
#   Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)
#
# von Gersdorff-Irges-Quiros break G by Lambda = diag(1_dH, -1_dK) and put the Wilson line along a
# BROKEN generator.  For su(N) with dH = N-1 that generator is the raising/lowering combination in
# the (1, N)-block, i.e. E_{alpha} + E_{-alpha} for the highest root alpha -- an su(2) subalgebra.
# Its eigenvalues in a representation are therefore the su(2) weights of the decomposition of that
# representation under the su(2) generated by the highest root: c = 2*lambda are the integers.

print("=" * 84)
print("vGIQ Wilson-line charges c = 2*lambda, from the su(2) generated by a broken generator")
print("=" * 84)

for N in (2, 3):
    g = LieAlgebra(QQ, cartan_type=['A', N - 1])
    # explicit matrices for the fundamental
    def fund_charges(N):
        # highest root su(2): T = (E_{1,N} + E_{N,1})/2 acting on C^N
        M = matrix(QQ, N, N)
        M[0, N - 1] = QQ(1) / 2
        M[N - 1, 0] = QQ(1) / 2
        return sorted([2 * r for r in M.eigenvalues()])

    def adj_charges(N):
        M = matrix(QQ, N, N)
        M[0, N - 1] = QQ(1) / 2
        M[N - 1, 0] = QQ(1) / 2
        # adjoint action on the traceless N x N matrices
        basis = []
        for i in range(N):
            for j in range(N):
                if i != j:
                    E = matrix(QQ, N, N); E[i, j] = 1
                    basis.append(E)
        for k in range(N - 1):
            E = matrix(QQ, N, N); E[k, k] = 1; E[k + 1, k + 1] = -1
            basis.append(E)
        n = len(basis)
        rows = []
        for B in basis:
            C = M * B - B * M
            v = []
            # expand C in `basis` by solving a linear system
            A = matrix(QQ, [b.list() for b in basis]).transpose()
            sol = A.solve_right(vector(QQ, C.list()))
            rows.append(sol)
        Mad = matrix(QQ, rows).transpose()
        return sorted([2 * r for r in Mad.eigenvalues()])

    cf, ca = fund_charges(N), adj_charges(N)
    CR = sum((QQ(c) / 2) ** 2 for c in cf)
    CG = sum((QQ(c) / 2) ** 2 for c in ca)
    print("SU(%d)" % N)
    print("   fundamental  c = %-28s   C_R    = %s   (textbook 1/2)" % (cf, CR))
    print("   adjoint      c = %-28s   C_2(G) = %s   (textbook %d)" % (ca, CG, N))
    print("   critical N_f, fundamental fermions : 3*C_G/(4*C_R) = %s" % (3 * CG / (4 * CR)))
    print("   critical N_f, adjoint     fermions : 3*C_G/(4*C_G) = %s" % (3 * CG / (4 * CG)))
    print()
print("vGIQ publish: N_f = 3 (SU(2) fund), 9/2 (SU(3) fund), 3/4 (adjoint).")
